f = open('sortiment.txt', 'a')
marke = input("Geben Sie die Marke ein: ")
modell = input("Geben Sie das Modell ein: ")
baujahr = input("Geben Sie das Baujahr ein: ")
preis = input("Geben Sie den Preis ein: ")
f.write(marke+"\n")
f.write(modell+"\n")
f.write(baujahr+"\n")
f.write(preis+"\n")
f.write("\n")

f = open('sortiment.txt', 'r')
inhalt = f.readlines()
print (inhalt)